"""add_ai_chat_messages_table

Revision ID: 796fbaf85db7
Revises: c93e2b7f4a18
Create Date: 2026-09-10 07:59:22.848491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796fbaf85db7'
down_revision: Union[str, None] = 'c93e2b7f4a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_messages',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_chat_messages_created_at', 'ai_chat_messages', ['created_at'], unique=False)
    op.create_index('ix_ai_chat_messages_user_id', 'ai_chat_messages', ['user_id'], unique=False)
    op.create_index('uq_system_category_name_type', 'categories', ['name', 'type'], unique=True, postgresql_where='is_system = true')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_system_category_name_type', table_name='categories', postgresql_where='is_system = true')
    op.drop_index('ix_ai_chat_messages_user_id', table_name='ai_chat_messages')
    op.drop_index('ix_ai_chat_messages_created_at', table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    # ### end Alembic commands ###
